apiVersion: apps/v1
kind: Deployment
metadata:
  name: version-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: version-app
  template:
    metadata:
      labels:
        app: version-app
    spec:
      containers:
      - name: version-app
        image: your-docker-repo/version-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: VERSION
          value: "1.0.0"
        - name: BUILD_SHA
          value: "abc57858585"
